### ISSUE TITLE
Eslint is not working

### ISSUE THREAD

**Issue by cropup** [NarHakobyan/awesome-nest-boilerplate#365]
Run ESLint
```
  Oops! Something went wrong! :(
  
  ESLint: 9.21.0
  
  Error: Cannot find module 'eslint-config-prettier/prettier'
  Require stack:
  - /home/runner/work/scraper/scraper/node_modules/eslint-plugin-prettier/recommended.js
      at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
      at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
      at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
      at Function._load (node:internal/modules/cjs/loader:1211:37)
      at TracingChannel.traceSync (node:diagnostics_channel:322:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
      at Module.require (node:internal/modules/cjs/loader:1487:12)
      at require (node:internal/modules/helpers:135:16)
      at Object.<anonymous> (/home/runner/work/scraper/scraper/node_modules/eslint-plugin-prettier/recommended.js:4:5)
      at Module._compile (node:internal/modules/cjs/loader:1730:14)
```

**Comment by NarHakobyan** [comment]
Fixed.

**Comment by cropup** [comment]
<img width="990" alt="Image" src="https://github.com/user-attachments/assets/e5600180-b04b-4c59-b72e-d5e9d95d3dd1" />

@NarHakobyan no, it's not fixed, as you see on the screenshot

**Comment by NarHakobyan** [comment]
See error message
